#!/bin/bash

echo ""
echo "------------------------"
echo ""
echo "cmd: /usr/bin/ruby -e \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)\""
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install autoconf"
brew install autoconf
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install cask"
brew install cask
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install coreutils"
brew install coreutils
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install cowsay"
brew install cowsay
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install cscope"
brew install cscope
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install eigen"
brew install eigen
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install emacs"
brew install emacs
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install ffmpeg"
brew install ffmpeg
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install freetype"
brew install freetype
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install fzf"
brew install fzf
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install gdbm"
brew install gdbm
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install gettext"
brew install gettext
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install git"
brew install git
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install icu4c"
brew install icu4c
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install ilmbase"
brew install ilmbase
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install imagemagick"
brew install imagemagick
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install jpeg"
brew install jpeg
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install lame"
brew install lame
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install leptonica"
brew install leptonica
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install libidn2"
brew install libidn2
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install libpng"
brew install libpng
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install libtiff"
brew install libtiff
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install libtool"
brew install libtool
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install libunistring"
brew install libunistring
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install libyaml"
brew install libyaml
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install macvim"
brew install macvim
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install node"
brew install node
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install numpy"
brew install numpy
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install opencv"
brew install opencv
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install openexr"
brew install openexr
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install openssl"
brew install openssl
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install perl"
brew install perl
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install phantomjs"
brew install phantomjs
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install pkg-config"
brew install pkg-config
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install pyenv"
brew install pyenv
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install python"
brew install python
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install python3"
brew install python3
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install rbenv"
brew install rbenv
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install readline"
brew install readline
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install ruby"
brew install ruby
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install ruby-build"
brew install ruby-build
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install sl"
brew install sl
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install speedtest-cli"
brew install speedtest-cli
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install sqlite"
brew install sqlite
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install tbb"
brew install tbb
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install tesseract"
brew install tesseract
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install tree"
brew install tree
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install vim"
brew install vim
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install wget"
brew install wget
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install x264"
brew install x264
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install xvid"
brew install xvid
echo ""
echo "------------------------"
echo ""
echo ""
echo "------------------------"
echo ""
echo "cmd: brew install xz"
brew install xz
echo ""
echo "------------------------"
echo ""
